---
name: Build docker images
on:
  schedule:
    - cron: 39 12 * * 0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out own repository
        uses: actions/checkout@v2
        with:
          path: patches
      - name: Check out musicbrainz-docker
        uses: actions/checkout@v2
        with:
          repository: metabrainz/musicbrainz-docker
      - name: Apply patches
        run:
          git apply patches/image_names.patch
      - name: Set up docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push MB production docker images
        env:
          MUSICBRAINZ_SERVER_VERSION: production
          REGISTRY_PREFIX: ghcr.io/ROpdebee/
        run:
          docker compose build
          docker compose push
      - name: Build and push MB beta docker images
        env:
          MUSICBRAINZ_SERVER_VERSION: beta
          REGISTRY_PREFIX: ghcr.io/ROpdebee/
        run:
          docker compose build
          docker compose push
      - name: Open issue if build failed
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: patches/.github/build-failure.md
          update_existing: true
          search_existing: open
