---
name: Build docker images

on:
  schedule:
    - cron: 39 12 * * 0
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-postgres:
    runs-on: ubuntu-latest
    env:
      POSTGRES_VERSION: 12
      IMAGE_TAG: ghcr.io/ropdebee/musicbrainz-docker_db:12
      CACHE_TAG: ghcr.io/ropdebee/musicbrainz-docker_db:buildcache

    steps:
      - name: Check out own repository for patch
        uses: actions/checkout@v3

      - name: Check out musicbrainz-docker
        uses: actions/checkout@v3
        with:
          repository: metabrainz/musicbrainz-docker
          path: musicbrainz-docker

      - name: Apply postgres patch for multistage build
        run: git apply ../002-postgres_multistage_build.patch
        working-directory: musicbrainz-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: musicbrainz-docker/build/postgres
          build-args: |
            POSTGRES_VERSION=${{ env.POSTGRES_VERSION }}
          shm-size: 2g
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.CACHE_TAG }},mode=max

  build-indexer:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ghcr.io/ropdebee/musicbrainz-docker_sir:latest
      CACHE_TAG: ghcr.io/ropdebee/musicbrainz-docker_sir:buildcache

    steps:
      - name: Check out musicbrainz-docker
        uses: actions/checkout@v3
        with:
          repository: metabrainz/musicbrainz-docker
          path: musicbrainz-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: musicbrainz-docker/build/sir
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.CACHE_TAG }},mode=max

  build-search:
    runs-on: ubuntu-latest
    env:
      MB_SOLR_VERSION: '3.4.2'
      IMAGE_TAG: ghcr.io/ropdebee/musicbrainz-docker_search:3.4.2
      CACHE_TAG: ghcr.io/ropdebee/musicbrainz-docker_search:buildcache

    steps:
      - name: Check out musicbrainz-docker
        uses: actions/checkout@v3
        with:
          repository: metabrainz/musicbrainz-docker
          path: musicbrainz-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: musicbrainz-docker/build/solr
          build-args: |
            MB_SOLR_VERSION=${{ env.MB_SOLR_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.CACHE_TAG }},mode=max

  build-mq:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ghcr.io/ropdebee/musicbrainz-docker_mq:latest
      CACHE_TAG: ghcr.io/ropdebee/musicbrainz-docker_mq:buildcache

    steps:
      - name: Check out musicbrainz-docker
        uses: actions/checkout@v3
        with:
          repository: metabrainz/musicbrainz-docker
          path: musicbrainz-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: musicbrainz-docker/build/rabbitmq
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.CACHE_TAG }},mode=max

  build-musicbrainz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - production
          - beta
    env:
      IMAGE_TAG: ghcr.io/ropdebee/musicbrainz-docker_musicbrainz:${{ matrix.version }}
      CACHE_TAG: ghcr.io/ropdebee/musicbrainz-docker_musicbrainz:${{ matrix.version }}-buildcache
      POSTGRES_VERSION: 12
      MUSICBRAINZ_WEB_SERVER_HOST: localtest.musicbrainz.org
      MUSICBRAINZ_WEB_SERVER_PORT: 443
      MUSICBRAINZ_STANDALONE_SERVER: 1

    steps:
      - name: Check out own repository for patch
        uses: actions/checkout@v3

      - name: Check out musicbrainz-docker
        uses: actions/checkout@v3
        with:
          repository: metabrainz/musicbrainz-docker
          path: musicbrainz-docker

      - name: Apply patch for prebuilt static resources
        run: git apply ../003-mb-static-resources.patch
        working-directory: musicbrainz-docker

      # We use a custom Dockerfile to build MBS which improves cacheability.
      # The original Dockerfile clones the MBS repository during the build
      # itself. When caching is enabled, it will never run the checkout again.
      # Our custom Dockerfile also installs dependencies before copying over
      # the source code, therefore allowing the build to reuse the cached
      # layers if dependencies haven't changed, while source code has.
      - name: Apply incremental build Dockerfile
        run: >-
          mv -f
          Dockerfile.mbs-incremental
          musicbrainz-docker/build/musicbrainz/Dockerfile

      # This wil prevent the .git directory from being in the image. The
      # (relatively small) space savings are nice, but this is mainly to
      # prevent layers from changing every time we clone the repository and
      # rebuild the image.
      - name: Apply MBS .dockerignore
        run: >-
          mv -f
          dockerignore.mbs
          musicbrainz-docker/build/musicbrainz/.dockerignore

      - name: Check out musicbrainz-server
        uses: actions/checkout@v3
        with:
          repository: metabrainz/musicbrainz-server
          path: musicbrainz-docker/build/musicbrainz/musicbrainz-server
          ref: ${{ matrix.version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: musicbrainz-docker/build/musicbrainz
          build-args: |
            POSTGRES_VERSION=${{ env.POSTGRES_VERSION }}
            MUSICBRAINZ_SERVER_VERSION=${{ matrix.version }}
            MUSICBRAINZ_WEB_SERVER_HOST=${{ env.MUSICBRAINZ_WEB_SERVER_HOST }}
            MUSICBRAINZ_WEB_SERVER_PORT=${{ env.MUSICBRAINZ_WEB_SERVER_PORT }}
            MUSICBRAINZ_STANDALONE_SERVER=${{ env.MUSICBRAINZ_STANDALONE_SERVER }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.CACHE_TAG }},mode=max

  report-failures:
    runs-on: ubuntu-latest
    needs:
      - build-postgres
      - build-musicbrainz
      - build-mq
      - build-search
      - build-indexer
    if: failure()
    steps:
      - name: Clone repository for issue template
        uses: actions/checkout@v3

      - name: Open issue if build failed
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/build-failure.md
          update_existing: true
          search_existing: open
