---
name: Build docker images
on:
  schedule:
    - cron: 39 12 * * 0
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out own repository
        uses: actions/checkout@v2
      - name: Check out musicbrainz-docker
        uses: actions/checkout@v2
        with:
          repository: metabrainz/musicbrainz-docker
          path: musicbrainz-docker
      - name: Apply patches
        run:
          for patch in ../*.patch; do git apply "$patch"; done
        working-directory: musicbrainz-docker
      - name: Pull previous version of images
        env:
          REGISTRY_PREFIX: ghcr.io/ropdebee/
        run: docker compose pull --ignore-pull-failures
        working-directory: musicbrainz-docker
      - name: Set up docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: docker-cache-{hash}
          restore-keys: |
            docker-cache-
        continue-on-error: true
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push MB production docker images
        env:
          MUSICBRAINZ_SERVER_VERSION: production
          MUSICBRAINZ_WEB_SERVER_HOST: localtest.musicbrainz.org
          MUSICBRAINZ_WEB_SERVER_PORT: 443
          REGISTRY_PREFIX: ghcr.io/ropdebee/
        run: |
          docker compose build
          docker compose push
        working-directory: musicbrainz-docker
      - name: Build and push MB beta docker images
        env:
          MUSICBRAINZ_SERVER_VERSION: beta
          REGISTRY_PREFIX: ghcr.io/ropdebee/
        run: |
          docker compose build
          docker compose push
        working-directory: musicbrainz-docker
      - name: Open issue if build failed
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/build-failure.md
          update_existing: true
          search_existing: open
